[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  # Skip secrets scanning for build outputs since Vite embeds env vars in client code
  SECRETS_SCAN_OMIT_PATHS = "dist/assets/*.js,dist/*.html"

# Environment variables are configured in Netlify dashboard
# The following VITE_ prefixed variables are available:
# VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY, VITE_GEMINI_API_KEY, VITE_APP_PASSWORD

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

